load '/Users/dhs/Downloads/Installed_soft/flutter-sdk/flutter/packages/flutter_tools/bin/podhelper.rb'

platform :ios, '15.5'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      # 1. Ensure all pods target iOS 15.5+ for ML Kit compatibility
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
      
      # 2. Exclude arm64 for simulators to allow building on Silicon Macs (using Rosetta)
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      
      # 3. Disable ONLY_ACTIVE_ARCH for pods
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'

      # 4. Enable Camera permissions
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1'
      ]
    end
  end

  installer.aggregate_targets.each do |target|
    target.user_project.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1'
      ]
    end
    target.user_project.save
  end
end